"""empty message

Revision ID: ad15ef3317a6
Revises: 
Create Date: 2019-09-09 07:24:22.448481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad15ef3317a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_state',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('most_common_height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('most_common_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height_distribution', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timeout_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nodes_tested', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='network_state_pkey')
    )
    # ### end Alembic commands ###
